### ISSUE TITLE
Encrypt accounts with backup password

### ISSUE THREAD

**Issue by jlcvp** [jlcvp/AuthLeu#7]
## Description
The app should be able to optionally encrypt/decrypt the secrets of the accounts with a user password without.
Users must be warned the accounts will be lost if they lose the password.

## Subtasks

- [ ] Encrypt/decrypt logic
- [ ] Import/Export handling
- [ ] Ask for password on account loading
- [ ] Optionally save password on local storage
- [ ] Informational alerts when setting up the password
- [ ] Migration from password-less version
- [ ] Detect unencrypted base and ask the users if they want to encrypt the data
